<?php

session_start();
if (!isset($_SESSION['username'])) {
    header("Location: login.php");
    die();
    exit();
}
?>

<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>AlertEd — Earthquake • Flood • Fire — All-in-One</title>
<link rel="icon" href="img/icon.jpg" type="image/x-icon">
<meta name="description" content="AlertEd: single-file interactive trainer for Earthquake, Flood and Fire. One-question-at-a-time quizzes with animations and synthesized audio.">
<style>
/* ===========================================================
   AlertEd — All-in-One Single File
   Theme: India tricolor (Orange / White / Green)
   Modules: Earthquake, Flood, Fire
   Features:
     - One-question-at-a-time quizzes
     - Animated school reactions: shake, collapse, flood, fire+smoke
     - Synthesized audio (Web Audio API) -> no external files required
     - XP, badges, dashboard, region selector, printable cards
     - Large precaution library generated by JS for readability
   =========================================================== */

/* ---------- root variables ---------- */
:root{
  --orange: #ff9933;
  --green:  #138808;
  --white:  #ffffff;
  --bg:     #fffdf9;
  --muted:  #475569;
  --card:   #ffffff;
  --shadow: 0 12px 36px rgba(2,6,23,0.08);
  --maxW:   1200px;
  --radius: 12px;
  --ease: cubic-bezier(.22,.9,.33,1);
}

/* ---------- reset ---------- */
*{box-sizing:border-box}
html,body{height:100%}
body{
  margin:0;
  font-family:Inter,system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial;
  background:linear-gradient(180deg,#ffffff 0%,var(--bg) 100%);
  color:#042b2a;padding:18px;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;
  line-height:1.45;
}

/* ---------- container & header ---------- */
.container{max-width:var(--maxW);margin:0 auto}
.header{display:flex;align-items:center;justify-content:space-between;padding:12px;border-radius:var(--radius);background:linear-gradient(90deg,var(--orange),#ffffff 48%,var(--green));box-shadow:var(--shadow)}
.brand{display:flex;gap:12px;align-items:center}
.logo{width:66px;height:66px;border-radius:12px;background:linear-gradient(135deg,var(--orange),var(--green));display:flex;align-items:center;justify-content:center;font-weight:900;color:#041025}
.title h1{margin:0;font-size:20px}
.title p{margin:0;font-size:12px;color:var(--muted)}
.nav{display:flex;gap:8px;flex-wrap:wrap}
.nav button{padding:8px 12px;border-radius:10px;border:none;background:rgba(0,0,0,0.04);cursor:pointer;font-weight:700}
.nav button.active{background:#fff;box-shadow:0 8px 20px rgba(0,0,0,0.06)}
.nav button:hover{transform:translateY(-3px);transition:all .12s ease}

/* ---------- layout ---------- */
.grid{display:grid;grid-template-columns:320px 1fr;gap:18px;margin-top:18px}
@media(max-width:980px){.grid{grid-template-columns:1fr}.logo{display:none}}
.sidebar{background:var(--card);border-radius:12px;padding:12px;box-shadow:var(--shadow);border:1px solid rgba(0,0,0,0.03)}
.profile{display:flex;gap:10px;align-items:center}
.avatar{width:56px;height:56px;border-radius:8px;background:linear-gradient(180deg,#fff3d1,#ffb86b);display:flex;align-items:center;justify-content:center;font-weight:800;color:#3a170a}
.small{font-size:13px;color:var(--muted)}

/* ---------- card ---------- */
.card{background:var(--card);border-radius:10px;padding:12px;margin-bottom:12px;box-shadow:0 8px 24px rgba(5,15,20,0.04);border:1px solid rgba(0,0,0,0.03)}
.card h3{margin:0 0 8px 0}

/* ---------- pages ---------- */
section.page{display:none}
section.page.active{display:block;animation:fadeIn .36s ease}
@keyframes fadeIn{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}

/* ---------- buttons ---------- */
.btn{padding:10px 14px;border-radius:10px;border:none;cursor:pointer;font-weight:700}
.btn.primary{background:linear-gradient(90deg,var(--orange),#ffb84d);color:#041025}
.btn.ghost{background:transparent;border:1px solid rgba(0,0,0,0.06);color:var(--muted)}
.btn.green{background:linear-gradient(90deg,#18a43f,var(--green));color:#fff}

/* ---------- progress ---------- */
.progressBar{height:12px;background:rgba(0,0,0,0.04);border-radius:8px;overflow:hidden}
.progressBar>i{display:block;height:100%;background:linear-gradient(90deg,var(--orange),var(--green))}

/* ---------- info styles ---------- */
.infoBlock{margin-top:12px;padding:12px;border-left:6px solid var(--orange);background:linear-gradient(180deg, rgba(255,255,255,0.98), rgba(255,255,255,0.95));border-radius:8px}
.infoBlock h4{margin:0 0 8px 0;color:var(--green)}
.infoList{margin:8px 0;padding-left:18px;color:var(--muted)}
.scrollY{max-height:260px;overflow:auto;padding-right:6px}

/* =============================================================
   EARTHQUAKE STYLES
   ============================================================= */
.eq-area{background:linear-gradient(180deg,#fff8f0,#fff2e6);border-radius:12px;padding:14px;border:1px solid rgba(0,0,0,0.03)}
.eq-ground{height:360px;border-radius:12px;background:linear-gradient(180deg,#fff6ee,#fff0e0);position:relative;display:flex;align-items:center;justify-content:center;overflow:hidden}
.building{width:420px;height:170px;border-radius:12px;background:linear-gradient(180deg,#fff,#fff8ef);display:flex;align-items:center;justify-content:center;font-weight:900;color:#0a2b2a;z-index:6;box-shadow:0 18px 40px rgba(0,0,0,0.06);transition:transform .18s var(--ease),filter .15s;transform-origin:50% 64%;position:relative}
.ground-crack{position:absolute;bottom:26px;left:10%;right:10%;height:4px;background:repeating-linear-gradient(90deg,#e8c9b0,#e8c9b0 6px,transparent 6px,transparent 12px);opacity:0;transition:opacity .25s}
.mud-splash{position:absolute;bottom:-40px;left:50%;transform:translateX(-50%);width:260px;height:110px;background:radial-gradient(circle at 50% 0%, rgba(255,153,51,0.95), rgba(19,136,8,0.0));border-radius:50%;opacity:0;transition:opacity .2s,transform .2s}

/* shaking */
.shake-slow{animation:shakeSlow 1s linear infinite}
.shake-med{animation:shakeMed .6s linear infinite}
.shake-fast{animation:shakeFast .28s linear infinite}
@keyframes shakeSlow{0%{transform:translate(0,0) rotate(0)}12%{transform:translate(-4px,-2px) rotate(-0.6deg)}25%{transform:translate(4px,2px) rotate(0.6deg)}37%{transform:translate(-3px,1px) rotate(-0.4deg)}50%{transform:translate(3px,-1px) rotate(0.4deg)}62%{transform:translate(-2px,2px) rotate(-0.2deg)}75%{transform:translate(2px,-2px) rotate(0.2deg)}100%{transform:translate(0,0) rotate(0)}}
@keyframes shakeMed{0%{transform:translate(0,0)}10%{transform:translate(-6px,-3px)}20%{transform:translate(6px,3px)}30%{transform:translate(-5px,2px)}40%{transform:translate(5px,-2px)}50%{transform:translate(-4px,3px)}60%{transform:translate(4px,-3px)}70%{transform:translate(-3px,2px)}80%{transform:translate(3px,-1px)}100%{transform:translate(0,0)}}
@keyframes shakeFast{0%{transform:translate(0,0)}10%{transform:translate(-12px,-6px)}20%{transform:translate(12px,6px)}30%{transform:translate(-10px,5px)}40%{transform:translate(10px,-5px)}50%{transform:translate(-8px,5px)}60%{transform:translate(8px,-6px)}70%{transform:translate(-6px,4px)}80%{transform:translate(6px,-4px)}90%{transform:translate(-4px,2px)}100%{transform:translate(0,0)}}

/* tilt & collapse */
.tilt-left{transform:rotate(-8deg) translateY(6px)}
.tilt-right{transform:rotate(8deg) translateY(6px)}
.fall{transform:translateY(120px) rotate(60deg);transition:transform 1s cubic-bezier(.2,.9,.3,1)}

/* =============================================================
   FLOOD STYLES
   ============================================================= */
.flood-area{background:linear-gradient(180deg,#f2fbff,#e8fbff);border-radius:12px;padding:14px;border:1px solid rgba(0,0,0,0.03)}
.school-wrap{height:300px;border-radius:12px;background:linear-gradient(180deg,#ffffff,#f0fbff);position:relative;overflow:hidden;border:1px solid rgba(0,0,0,0.02)}
.school-box{position:absolute;left:50%;transform:translateX(-50%);bottom:22px;width:360px;height:140px;background:linear-gradient(180deg,#fff,#fffbf0);border-radius:10px;display:flex;align-items:center;justify-content:center;font-weight:900;color:#0b2b28;z-index:6;box-shadow:0 12px 30px rgba(0,0,0,0.06)}
.water-layer{position:absolute;left:0;bottom:0;width:100%;height:0;z-index:3;background:linear-gradient(180deg,#4fc3f7,#0288d1);transition:height .9s ease}
.wave{position:absolute;left:0;width:200%;height:120px;border-radius:40%;opacity:0.45;background:rgba(255,255,255,0.75)}
.wave.w1{bottom:-20px;transform:translateX(-20%);animation:waveMove 6s linear infinite}
.wave.w2{bottom:-44px;transform:translateX(0);animation:waveMove 4.2s linear infinite}
@keyframes waveMove{0%{transform:translateX(-20%)}100%{transform:translateX(20%)}}
.float{position:absolute;z-index:7;transition:bottom 900ms ease,transform 400ms ease;cursor:pointer}
.float.saved{transform:scale(.85) rotate(-6deg);opacity:0.75;pointer-events:none}

/* =============================================================
   FIRE STYLES
   ============================================================= */
.fire-area{background:linear-gradient(180deg,#fffaf0,#fff3e6);border-radius:12px;padding:14px;border:1px solid rgba(0,0,0,0.03)}
.fire-wrap{height:300px;border-radius:12px;background:linear-gradient(180deg,#fffef8,#fff7ee);position:relative;overflow:hidden;border:1px solid rgba(0,0,0,0.02)}
.fire-school{position:absolute;left:50%;transform:translateX(-50%);bottom:22px;width:360px;height:140px;background:linear-gradient(180deg,#fff,#fffbf0);border-radius:10px;display:flex;align-items:center;justify-content:center;font-weight:900;color:#0b2b28;z-index:6;box-shadow:0 12px 30px rgba(0,0,0,0.06)}
.flames{position:absolute;left:50%;transform:translateX(-50%);bottom:86px;width:240px;height:120px;pointer-events:none;z-index:8;opacity:0;transition:opacity 400ms}
.flame{position:absolute;bottom:0;left:50%;transform:translateX(-50%);width:60px;height:100px;border-radius:50% 50% 20% 20%;background:linear-gradient(180deg,#ff6b00,#ffcc00);filter:blur(6px);animation:flameMove 900ms ease-in-out infinite}
.flame.f1{left:32%;width:40px;height:80px;animation-duration:800ms}
.flame.f2{left:50%;width:60px;height:110px;animation-duration:900ms}
.flame.f3{left:68%;width:44px;height:88px;animation-duration:760ms}
@keyframes flameMove{0%{transform:translateX(0) translateY(0) scale(1)}50%{transform:translateX(0) translateY(-8px) scale(1.05)}100%{transform:translateX(0) translateY(0) scale(1)}}
.smoke{position:absolute;right:12%;top:6%;width:80px;height:40px;border-radius:50%;background:linear-gradient(180deg,rgba(0,0,0,0.06),rgba(0,0,0,0.18));opacity:0;transform:translateY(0);animation:smokeRise 2000ms linear infinite}
@keyframes smokeRise{0%{opacity:0;transform:translateY(0) scale(0.8)}30%{opacity:0.25}60%{opacity:0.5;transform:translateY(-14px) scale(1.1)}100%{opacity:0;transform:translateY(-40px) scale(1.4)}}

/* ---------- misc ---------- */
.leader { display:flex; align-items:center; gap:8px; padding:10px; border-radius:8px; background:linear-gradient(180deg,#fff,#fffef7); }
.regionCard{padding:10px;border-radius:8px;border:1px solid rgba(0,0,0,0.03);cursor:pointer}
.regionCard:hover{transform:translateY(-4px);transition:all .12s ease}

/* accessibility */
:focus{outline:3px solid rgba(19,136,8,0.12);outline-offset:2px;border-radius:6px}

/* small screen tweaks */
@media(max-width:700px){
  .building{width:300px;height:120px}
  .school-box,.fire-school{width:280px;height:110px}
  .logo{width:48px;height:48px}
}
</style>
</head>
<body>
<div class="container">
  <header class="header" role="banner">
    <div class="brand">
      <div class="logo"><img style="width: 66px; border-radius: 12px" src="img/icon.jpg" alt="Logo" ></div>
      <div class="title">
        <h1>AlertEd - Earthquake•Flood•Fire</h1>
        <p>Interactive school safety trainer</p>
      </div>
    </div>

    <nav class="nav" role="navigation" aria-label="main">
      <button class="navBtn active" data-page="home">Home</button>
      <button class="navBtn" data-page="disaster">Disasters and Quizzes</button>
      <button class="navBtn" data-page="regions">Regions</button>
      <button class="navBtn" data-page="safety">Safety</button>
      <button class="navBtn" data-page="dashboard">Dashboard</button>
      <button class="navBtn" data-page="map">Map</button>
    </nav>
  </header>

  <div class="grid" role="main">
    <!-- SIDEBAR -->
    <aside class="sidebar" role="complementary">
      <div class="profile">
        <?php echo '<div class="avatar">' . substr($_SESSION['username'],0,1) . '</div>'; ?>
        <div>
          <?php echo "<div style='font-weight:800;'>" . $_SESSION['username'] . "</div>"; ?>
        </div>
      </div>

      <div class="card" style="margin-top:12px">
        <div style="display:flex;justify-content:space-between;align-items:center">
          <div>
            <div style="font-weight:800">Preparedness</div>
          </div>
          <div style="font-weight:900" id="prepVal">0%</div>
        </div>
        <div style="margin-top:10px" class="progressBar"><i id="prepBar" style="width:78%;display:block;height:12px;border-radius:8px;background:linear-gradient(90deg,var(--orange),var(--green))"></i></div>
      </div>

      <div class="card small">
        <div style="display:flex;justify-content:space-between;align-items:center">
          <div>
            <div style="font-weight:800">XP</div>
            <div class="small">Earn in quizzes</div>
          </div>
          <div style="font-weight:900" id="xpVal">520</div>
        </div>
      </div>

      <div class="card small">
        <div style="font-weight:800">Badges</div>
        <div style="display:flex;gap:8px;margin-top:8px;flex-wrap:wrap">
          <div id="badge1" style="padding:6px 8px;border-radius:8px;background:linear-gradient(90deg,var(--orange),var(--green));color:#041025;font-weight:800">Disaster Learner</div>
          <div id="badge2" style="padding:6px 8px;border-radius:8px;background:rgba(0,0,0,0.04);">—</div>
        </div>
      </div>

      <div class="card small">
        <div style="font-weight:800">Quick Actions</div>
        <div style="display:flex;flex-direction:column;gap:8px;margin-top:8px">
          <button class="btn ghost" onclick="startEqQuiz()">Start EQ Quiz</button>
          <button class="btn ghost" onclick="startFloodQuiz()">Start Flood Quiz</button>
          <button class="btn ghost" onclick="startFireQuiz()">Start Fire Quiz</button>
          <button class="btn green" onclick="startDrill()">Run Quick Drill</button>
        </div>
      </div>

      <div class="card small">
        <div style="font-weight:800">Tip</div>
        <div class="small" id="tipText" style="margin-top:8px">Keep emergency contact list printed and online.</div>
      </div>

      <div class="card small">
        <div style="font-weight:800">Local Contacts</div>
        <div class="small" style="margin-top:6px">Emergency: <strong>108</strong> • Fire: <strong>101</strong></div>
      </div>

    </aside>

    <!-- MAIN CONTENT -->
    <main>

      <!-- HOME -->
      <section id="home" class="page active">
        <div class="card">
          <h2 style="margin:0">Welcome to AlertEd</h2>
          <p class="small" style="color:var(--muted);margin-top:8px">Learn by doing: answer one question at a time. Correct answers stabilize or reduce hazards; wrong answers escalate the simulation. Built for hackathons and classroom demos.</p>
          <div style="margin-top:12px;display:flex;gap:10px">
            <button class="btn primary" onclick="goTo('earthquakeQuiz')">Play Earthquake Quiz</button>
            <button class="btn primary" onclick="goTo('floodQuiz')">Play Flood Quiz</button>
            <button class="btn primary" onclick="goTo('fireQuiz')">Play Fire Quiz</button>
          </div>
        </div>

        <div class="card infoBlock" style="margin-top:12px">
          <h4>Why this matters</h4>
          <div class="infoList">Many schools in India lack digital drills and region-specific preparedness. This single-file app offers quick quizzes, animations and sound feedback to train students and staff effectively.</div>
        </div>
        <div class="card" style="margin-top:12px;text-align: center;">
          <img src="img/fox.png" alt="Mascot" style="width: 25vw;border-radius: 1vw">
        </div>
        <div class="card" style="margin-top:12px">
          <h3>Features</h3>
          <ul class="infoList">
            <li>Earthquake: Drop, Cover & Hold On practice — building shakes & collapses in extremes.</li>
            <li>Flood: Rising water simulation, rescueable items, water physics feel.</li>
            <li>Fire: Flames, smoke, spread simulation, extinguish actions.</li>
            <li>Gamification: XP, badges, dashboard & printable safety cards.</li>
          </ul>
        </div>
      </section>

      <!--DISASTER MODULE-->
      <section id="disaster" class="page">
        <div class="card">
          <h3>Disasters & Quizzes</h3>
          <br>
          <nav class="nav" role="navigation">
            <button class="navBtn" data-page="earthquake">Earthquake</button>
            <button class="navBtn" data-page="earthquakeQuiz">Earthquake Quiz</button>
            <br>
            <button class="navBtn" data-page="flood">Flood</button>
            <button class="navBtn" data-page="floodQuiz">Flood Quiz</button>
            <br>
            <button class="navBtn" data-page="fire">Fire</button>
            <button class="navBtn" data-page="fireQuiz">Fire Quiz</button>
            <br>
          </nav>
        </div>
      </section>

      <!-- EARTHQUAKE MODULE -->
      <section id="earthquake" class="page">
        <div class="card eq-area">
          <div style="display:flex;gap:14px;align-items:flex-start">
            <div style="flex:1">
              <h3 style="margin-top:0">Earthquake Module (Mud Theme)</h3>
              <p class="small" style="color:var(--muted)">Practice earthquake-safe behaviour. Correct answers increase 'stability'; wrong answers increase shake intensity and can visually tilt/collapse the school model.</p>
              <div style="margin-top:12px;display:flex;gap:10px">
                <button class="btn primary" onclick="startEqQuiz()">Start Quiz</button>
                <button class="btn ghost" onclick="simulateShake('med')">Simulate Med Shake</button>
                <button class="btn ghost" onclick="simulateShake('fast')">Simulate Severe Shake</button>
                <button class="btn ghost" onclick="resetEarth()">Reset</button>
              </div>
              <div class="card" style="margin-top:12px;">
                <img src="img/earthquake.jpg" alt="EQ" style="width: 25vw;">
              </div>
              <div class="card infoBlock scrollY" style="margin-top:12px">
                <h4>Precautions — Classroom</h4>
                <ul class="infoList">
                  <li>Drop, Cover & Hold On immediately during shaking.</li>
                  <li>Keep emergency kit in classroom including water and first aid.</li>
                  <li>Designate wardens and alternate wardens for every class.</li>
                </ul>
              </div>
            </div>

            <div style="width:520px;position:relative">
              <div class="eq-ground" id="eqGround">
                <div class="building" id="buildingVisual">COMMUNITY<br/>SCHOOL</div>
                <div class="ground-crack" id="groundCrack"></div>
                <div class="mud-splash" id="mudSplash"></div>
              </div>

              <div class="card small" style="margin-top:12px">
                <div style="display:flex;justify-content:space-between;align-items:center">
                  <div>
                    <div style="font-weight:800">Stability</div>
                    <div class="small" style="color:var(--muted)">Higher is safer</div>
                  </div>
                  <div id="stabilityText" style="font-weight:900">80%</div>
                </div>
                <div style="margin-top:8px" class="progressBar"><i id="stabilityBar" style="width:80%;display:block;height:12px;border-radius:8px;background:linear-gradient(90deg,var(--orange),var(--green))"></i></div>
              </div>

            </div>
          </div>
        </div>

        <div class="card" style="margin-top:12px">
          <h4>Earthquake Guidance (Detailed)</h4>
          <div class="scrollY" style="max-height:240px;padding-right:6px">
            <p class="small" style="color:var(--muted)">Use this content to create posters and handouts. Drill frequency, roles, and post-event management are covered.</p>
            <ul class="infoList">
              <li>Secure shelves and heavy items to walls; keep heavy objects low.</li>
              <li>Practice evacuation routes; perform roll-calls after drills.</li>
              <li>Coordinate with local disaster authorities for large drills.</li>
            </ul>
          </div>
        </div>
      </section>

      <!-- EARTHQUAKE QUIZ -->
      <section id="earthquakeQuiz" class="page">
        <div class="card">
          <h3>Earthquake Quiz — One Question at a Time</h3>
          <p class="small" style="color:var(--muted)">Correct answers stabilize the building; wrong answers increase shaking and may tilt/collapse if stability low.</p>
          <div style="display:flex;gap:12px;align-items:center;margin-top:12px">
            <button class="btn primary" id="eqStartBtn">Start Quiz</button>
            <button class="btn ghost" id="eqNextBtn" disabled>Next</button>
            <button class="btn ghost" onclick="resetEarth()">Reset</button>
            <div style="margin-left:auto" class="small">EQ XP: <strong id="eqXP">0</strong></div>
          </div>

          <div class="card" style="margin-top:12px">
            <div id="eqQuestionArea">
              <div style="font-weight:900" id="eqQuestionTitle">Press Start to begin the Earthquake Quiz</div>
              <div id="eqChoices" style="margin-top:12px"></div>
            </div>
          </div>

          <div class="card" style="margin-top:12px">
            <div style="display:flex;justify-content:space-between;align-items:center">
              <div class="small">Score: <strong id="eqScore">0</strong></div>
              <div class="small">Question <span id="eqQNum">0</span> / <span id="eqTotal">0</span></div>
            </div>
          </div>
        </div>
      </section>

      <!-- FLOOD MODULE -->
      <section id="flood" class="page">
        <div class="card flood-area">
          <div style="display:flex;gap:14px;align-items:flex-start">
            <div style="flex:1">
              <h3 style="margin-top:0">Flood Module (Water Theme)</h3>
              <video src="vid/vid1.mp4" style="width: 30vw; border-radius: 1vw;" controls></video>
              <p class="small" style="color:var(--muted)">Correct answers lower water; wrong answers raise water. Rescue floats for bonus points.</p>
              <div style="margin-top:12px;display:flex;gap:10px">
                <button class="btn primary" onclick="startFloodQuiz()">Start Flood Quiz</button>
                <button class="btn ghost" onclick="changeWater(10)">Raise Water</button>
                <button class="btn ghost" onclick="changeWater(-10)">Lower Water</button>
                <button class="btn ghost" onclick="resetFlood()">Reset</button>
              </div>

              <div class="card" style="margin-top:12px;">
                <img src="img/flood.jpg" alt="FL" style="width: 25vw;">
              </div>

              <div class="card infoBlock scrollY" style="margin-top:12px">
                <h4>Flood Precautions (Short)</h4>
                <ul class="infoList">
                  <li>Move to higher ground when water threatens.</li>
                  <li>Avoid walking/driving through moving water.</li>
                  <li>Keep docs & medicines waterproofed on higher shelves.</li>
                </ul>
              </div>

            </div>

            <div style="width:520px;position:relative">
              <div class="school-wrap" id="schoolWrap">
                <div class="school-box">COMMUNITY SCHOOL</div>
                <div class="water-layer" id="waterLayer">
                  <div class="wave w1"></div>
                  <div class="wave w2"></div>
                </div>

                <img id="floatA" class="float" src="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='64' height='44'><rect rx='6' ry='6' width='64' height='44' fill='%23fde68a'/><text x='32' y='28' font-size='12' text-anchor='middle' fill='%23090f12'>Book</text></svg>" style="left:18%;bottom:40px;width:64px" alt="Book"/>
                <img id="floatB" class="float" src="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='72' height='48'><rect rx='8' ry='8' width='72' height='48' fill='%23bde0ff'/><text x='36' y='30' font-size='12' text-anchor='middle' fill='%23090f12'>Med</text></svg>" style="left:50%;bottom:64px;width:72px" alt="Med"/>
                <img id="floatC" class="float" src="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='50' height='50'><circle cx='25' cy='25' r='22' fill='%23ffb4b4'/><text x='25' y='30' font-size='12' text-anchor='middle' fill='%23090f12'>Toy</text></svg>" style="left:78%;bottom:46px;width:50px" alt="Toy"/>
              </div>

              <div class="card small" style="margin-top:12px">
                <div style="display:flex;justify-content:space-between;align-items:center">
                  <div>
                    <div style="font-weight:800">Water Level</div>
                    <div class="small" style="color:var(--muted)">Lower is safer</div>
                  </div>
                  <div id="waterPct" style="font-weight:900">20%</div>
                </div>
                <div style="margin-top:8px" class="progressBar"><i id="waterBar" style="width:20%;display:block;height:12px;border-radius:8px;background:linear-gradient(90deg,var(--green),var(--orange))"></i></div>
              </div>

            </div>
          </div>
        </div>

        <div class="card infoBlock" style="margin-top:12px">
          <h4>After-Flood Guidance</h4>
          <div class="scrollY" style="max-height:220px;padding-right:6px">
            <ul class="infoList">
              <li>Boil or purify water before drinking after floods.</li>
              <li>Sanitize surfaces and avoid contaminated food.</li>
              <li>Coordinate with local sanitation teams for long-duration floods.</li>
            </ul>
          </div>
        </div>
      </section>

      <!-- FLOOD QUIZ -->
      <section id="floodQuiz" class="page">
        <div class="card">
          <h3>Flood Quiz — One Question at a Time</h3>
          <p class="small" style="color:var(--muted)">Answer to influence water level and rescue items for bonus points.</p>
          <div style="display:flex;gap:12px;align-items:center;margin-top:12px">
            <button class="btn primary" id="fStartBtn">Start Flood Quiz</button>
            <button class="btn ghost" id="fNextBtn" disabled>Next</button>
            <button class="btn ghost" onclick="resetFlood()">Reset</button>
            <div style="margin-left:auto" class="small">Score: <strong id="fScore">0</strong></div>
          </div>

          <div class="card" style="margin-top:12px">
            <div id="fQuestionArea">
              <div style="font-weight:900" id="fQuestionTitle">Press Start to begin the Flood Quiz</div>
              <div id="fChoices" style="margin-top:12px"></div>
            </div>
          </div>

          <div class="card" style="margin-top:12px"><div class="small">Items rescued: <strong id="itemsRescued">0</strong></div></div>
        </div>
      </section>

      <!-- FIRE MODULE -->
      <section id="fire" class="page">
        <div class="card fire-area">
          <div style="display:flex;gap:14px;align-items:flex-start">
            <div style="flex:1">
              <h3 style="margin-top:0">Fire Module (Heat/Smoke Theme)</h3>
              <p class="small" style="color:var(--muted)">Correct answers reduce fire spread and extinguish flames; wrong answers let fire grow. Learn evacuation and extinguisher basics.</p>
              <div style="margin-top:12px;display:flex;gap:10px">
                <button class="btn primary" onclick="startFireQuiz()">Start Fire Quiz</button>
                <button class="btn ghost" onclick="igniteFire()">Ignite Small Fire</button>
                <button class="btn ghost" onclick="extinguishFire()">Attempt Extinguish</button>
                <button class="btn ghost" onclick="resetFire()">Reset</button>
              </div>

              <div class="card" style="margin-top:12px;">
                <img src="img/fire.jpg" alt="FR" style="width: 25vw;">
              </div>

              <div class="card infoBlock scrollY" style="margin-top:12px">
                <h4>Fire Precautions — Quick</h4>
                <ul class="infoList">
                  <li>Know two evacuation routes from every classroom.</li>
                  <li>Store flammable materials safely and away from power sources.</li>
                  <li>Have simple extinguishers & training for staff.</li>
                </ul>
              </div>
            </div>

            <div style="width:520px;position:relative">
              <div class="fire-wrap" id="fireWrap">
                <div class="fire-school" id="fireSchool">COMMUNITY SCHOOL</div>
                <div class="flames" id="flames">
                  <div class="flame f1"></div>
                  <div class="flame f2"></div>
                  <div class="flame f3"></div>
                </div>
                <div class="smoke" id="smoke"></div>
              </div>

              <div class="card small" style="margin-top:12px">
                <div style="display:flex;justify-content:space-between;align-items:center">
                  <div>
                    <div style="font-weight:800">Fire Level</div>
                    <div class="small" style="color:var(--muted)">Lower is safer</div>
                  </div>
                  <div id="firePct" style="font-weight:900">0%</div>
                </div>
                <div style="margin-top:8px" class="progressBar"><i id="fireBar" style="width:0%;display:block;height:12px;border-radius:8px;background:linear-gradient(90deg,#ff7a00,#ffcc00)"></i></div>
              </div>

            </div>
          </div>
        </div>

        <div class="card infoBlock" style="margin-top:12px">
          <h4>After-Fire Guidance</h4>
          <div class="scrollY" style="max-height:220px;padding-right:6px">
            <ul class="infoList">
              <li>Do not re-enter building until cleared by authorities.</li>
              <li>Provide first aid for burns and smoke inhalation.</li>
              <li>Coordinate with local fire department for repairs and investigation.</li>
            </ul>
          </div>
        </div>
      </section>

      <!-- FIRE QUIZ -->
      <section id="fireQuiz" class="page">
        <div class="card">
          <h3>Fire Quiz — One Question at a Time</h3>
          <p class="small" style="color:var(--muted)">Answer to reduce fire risk: correct reduces fire level; wrong increases spread.</p>

          <div style="display:flex;gap:12px;align-items:center;margin-top:12px">
            <button class="btn primary" id="fireStartBtn">Start Fire Quiz</button>
            <button class="btn ghost" id="fireNextBtn" disabled>Next</button>
            <button class="btn ghost" onclick="resetFire()">Reset</button>
            <div style="margin-left:auto" class="small">Score: <strong id="fiScore">0</strong></div>
          </div>

          <div class="card" style="margin-top:12px">
            <div id="fireQuestionArea">
              <div style="font-weight:900" id="fireQuestionTitle">Press Start to begin the Fire Quiz</div>
              <div id="fireChoices" style="margin-top:12px"></div>
            </div>
          </div>

        </div>
      </section>

      <!-- REGIONS -->
      <section id="regions" class="page">
        <div class="card">
          <h3>Regions — India-focused Guidance</h3>
          <p class="small" style="color:var(--muted)">Select a region to tailor quiz context and hazards.</p>
          <div style="margin-top:12px;display:grid;grid-template-columns:repeat(2,1fr);gap:10px">
            <div class="regionCard" onclick="selectRegion('Kerala')"><strong>Kerala</strong><div class="small">Monsoon floods — evacuation & boats</div></div>
            <div class="regionCard" onclick="selectRegion('Assam')"><strong>Assam</strong><div class="small">River floods & embankment awareness</div></div>
            <div class="regionCard" onclick="selectRegion('Odisha')"><strong>Odisha</strong><div class="small">Cyclones & coastal surge</div></div>
            <div class="regionCard" onclick="selectRegion('Himalayan')"><strong>Himalayan</strong><div class="small">Seismic & landslide risk</div></div>
            <div class="regionCard" onclick="selectRegion('Mumbai')"><strong>Mumbai</strong><div class="small">Urban flooding & drainage</div></div>
            <div class="regionCard" onclick="selectRegion('Rajasthan')"><strong>Rajasthan</strong><div class="small">Drought & water management</div></div>
          </div>

          <div class="card small" style="margin-top:12px">
            <strong>Selected Region:</strong> <span id="selectedRegion">National</span>
            <div id="regionNotes" class="small" style="color:var(--muted);margin-top:8px">No region selected — general quizzes will be used.</div>
          </div>
        </div>
      </section>

      <!--MAP-->
      <section id="map" class="page">
        <div class="card">
          <h3>Map</h3>
          <img src="map/map.jpg" alt="Map">
          <h3>Legend</h3>
          <img src="map/legend.jpg" alt="Legend">
        </div>
      </section>

      <!-- SAFETY -->
      <section id="safety" class="page">
        <div class="card">
          <h3>Safety Cards & Printables</h3>
          <p class="small" style="color:var(--muted)">Printable single-page cards for students & staff.</p>
          <div style="display:flex;gap:10px;margin-top:12px">
            <button class="btn primary" onclick="printCard('earthquake')">Print Earthquake Card</button>
            <button class="btn primary" onclick="printCard('flood')">Print Flood Card</button>
            <button class="btn primary" onclick="printCard('fire')">Print Fire Card</button>
          </div>

          <div class="card infoBlock" style="margin-top:12px">
            <h4>Extended Precautions Library</h4>
            <div class="scrollY" style="max-height:260px;padding-right:6px">
              <ul class="infoList" id="longPrecautionsList"></ul>
            </div>
          </div>
        </div>
      </section>

      <!-- DASHBOARD -->
      <section id="dashboard" class="page">
        <div class="card">
          <h3>Dashboard</h3>
          <div style="display:flex;gap:12px;flex-wrap:wrap;margin-top:12px">
            <div style="flex:1;min-width:260px" class="card small">
              <strong>Preparedness</strong>
              <div style="margin-top:8px" class="small">School Average</div>
              <div style="margin-top:8px" class="progressBar"><i id="prepBarInner" style="width:78%;display:block;height:12px;border-radius:8px;background:linear-gradient(90deg,var(--orange),var(--green))"></i></div>
              <div class="small" style="margin-top:8px">Drill participation: 0%</div>
            </div>
          </div>
        </div>
      </section>

    </main>
  </div>

  <div class="footer" style="text-align:center;margin-top:18px;color:var(--muted)">Prototype for SIH (replace placeholder content with local resources before production).</div>
</div>

<!-- ============================
     Web Audio Synth Helpers
     (no external audio files required)
     ============================ -->
<script>
const AudioCtx = window.AudioContext || window.webkitAudioContext;
const audioCtx = new AudioCtx();

/* pleasant two-note correct chime */
function correctTone(){
  const now = audioCtx.currentTime;
  const g = audioCtx.createGain(); g.gain.setValueAtTime(0.0001, now);
  const o = audioCtx.createOscillator(); o.type = 'sine';
  o.frequency.setValueAtTime(520, now);
  g.gain.linearRampToValueAtTime(0.08, now + 0.01);
  o.connect(g); g.connect(audioCtx.destination);
  o.start(now); o.frequency.exponentialRampToValueAtTime(720, now + 0.18);
  g.gain.exponentialRampToValueAtTime(0.0001, now + 0.5);
  o.stop(now + 0.55);
}

/* grating wrong buzzer */
function wrongTone(){
  const now = audioCtx.currentTime;
  const o = audioCtx.createOscillator(); o.type = 'square';
  const f = audioCtx.createBiquadFilter(); f.type = 'lowpass';
  f.frequency.setValueAtTime(1200, now);
  const g = audioCtx.createGain(); g.gain.setValueAtTime(0.12, now);
  o.connect(f); f.connect(g); g.connect(audioCtx.destination);
  o.frequency.setValueAtTime(160, now);
  g.gain.exponentialRampToValueAtTime(0.0001, now + 0.45);
  o.start(now); o.stop(now + 0.45);
}

/* earthquake rumble */
function shakeRumble(duration=700){
  const now = audioCtx.currentTime;
  const o1 = audioCtx.createOscillator(), o2 = audioCtx.createOscillator(), g = audioCtx.createGain();
  o1.type='sine'; o2.type='sine'; o1.frequency.setValueAtTime(40, now); o2.frequency.setValueAtTime(60, now);
  g.gain.setValueAtTime(0.0, now); g.gain.linearRampToValueAtTime(0.12, now + 0.02);
  g.gain.exponentialRampToValueAtTime(0.0001, now + duration/1000);
  o1.connect(g); o2.connect(g); g.connect(audioCtx.destination);
  o1.start(now); o2.start(now); o1.stop(now + duration/1000); o2.stop(now + duration/1000);
}

/* water plop */
function waterPlop(){
  const now = audioCtx.currentTime;
  const o = audioCtx.createOscillator(); const g = audioCtx.createGain();
  o.type = 'triangle'; o.frequency.setValueAtTime(420, now); g.gain.setValueAtTime(0.04, now);
  g.gain.exponentialRampToValueAtTime(0.0001, now + 0.6);
  o.connect(g); g.connect(audioCtx.destination); o.start(now); o.stop(now + 0.6);
}

/* fire crackle: short noise burst */
function fireCrackle(){
  const now = audioCtx.currentTime;
  const bufferSize = audioCtx.sampleRate * 0.5;
  const buffer = audioCtx.createBuffer(1, bufferSize, audioCtx.sampleRate);
  const data = buffer.getChannelData(0);
  for (let i=0;i<bufferSize;i++){
    data[i] = (Math.random()*2-1) * Math.exp(-i / (bufferSize*0.6)) * 0.4;
  }
  const src = audioCtx.createBufferSource(); src.buffer = buffer;
  const filter = audioCtx.createBiquadFilter(); filter.type='highpass'; filter.frequency.setValueAtTime(600, now);
  const g = audioCtx.createGain(); g.gain.setValueAtTime(0.6, now);
  src.connect(filter); filter.connect(g); g.connect(audioCtx.destination);
  src.start(now); src.stop(now + 0.6);
}
</script>

<!-- ============================
     Application Logic & Data
     ============================ -->
<script>
/* Global state */
const State = {
  region: 'National',
  xp: 520,
  badges: new Set(['Disaster Learner']),
  eq: { stability: 0, score: 0, xp: 0, qIdx: -1 },
  flood: { water: 0, score: 0, items: 0, qIdx: -1 },
  fire: { level: 0, score: 0, qIdx: -1 },
  eqQuestions: [], floodQuestions: [], fireQuestions: [],
  longPrecautions: []
};

/* DOM helpers */
const $ = s => document.querySelector(s);
const $$ = s => Array.from(document.querySelectorAll(s));

/* Navigation wiring */
$$('.navBtn').forEach(btn => btn.addEventListener('click', ()=>{
  $$('.navBtn').forEach(b=>b.classList.remove('active'));
  btn.classList.add('active');
  const page = btn.dataset.page;
  $$('.page').forEach(p=>p.classList.remove('active'));
  const el = document.getElementById(page);
  if(el) el.classList.add('active');
  window.scrollTo({top:0,behavior:'smooth'});
}));

function goTo(page){ const btn=$$('.navBtn').find(b=>b.dataset.page===page); if(btn) btn.click(); }

/* Tip rotator */
const tips = [
  'Keep an emergency kit in a waterproof container.',
  'Run monthly mini-drills with students.',
  'Post evacuation maps at classroom doors.',
  'Keep contact lists updated and laminated.'
];
let tipIdx = 0;
setInterval(()=>{ tipIdx=(tipIdx+1)%tips.length; $('#tipText').textContent = tips[tipIdx]; },7000);

/* Seed question banks (several dozen each) */
(function seedBanks(){
  const eqBase = [
    { q: "During shaking, what is the safest immediate action?", choices:["Run outside","Drop, Cover & Hold On","Stand near windows","Climb on desk"], correct:1 },
    { q: "If outside during shaking, where should you move?", choices:["Under tree","Open ground away from buildings","Near powerlines","Into vehicle"], correct:1 },
    { q: "Which is unsafe during earthquake?", choices:["Stay near glass","Drop & cover","Hold on","Stay low"], correct:0 },
    { q: "Who should take roll-call after drill?", choices:["Teachers","Students only","Visitors","Cooks"], correct:0 }
  ];
  const fqBase = [
    { q: "When flood water rises quickly what do you do first?", choices:["Collect belongings","Move to higher ground","Stay in basement","Open windows"], correct:1 },
    { q: "Should you walk through moving flood water?", choices:["Never","Sometimes","If shallow","In groups"], correct:0 },
    { q: "Where to keep emergency medicines?", choices:["On floor","Waterproof bag on high shelf","Basement","Outside"], correct:1 }
  ];
  const fiBase = [
    { q: "If you see smoke in classroom, first action?", choices:["Open windows","Sound alarm and evacuate","Search for fire extinguisher","Hide under desk"], correct:1 },
    { q: "Which extinguisher to use for electrical fire?", choices:["Water","CO2/ Dry Powder","Sand","Any"], correct:1 },
    { q: "Where to store flammables in school?", choices:["Near lights","In locked metal cabinet","On windowsill","On floor"], correct:1 }
  ];

  // expand to large banks by duplication with variation
  let eq=[], fq=[], fi=[];
  for(let i=0;i<30;i++){
    eq = eq.concat(eqBase.map((x,idx)=>({...x, q: x.q + ' (Q' + (i+1) + ')'})));
    fq = fq.concat(fqBase.map((x,idx)=>({...x, q: x.q + ' (Q' + (i+1) + ')'})));
    fi = fi.concat(fiBase.map((x,idx)=>({...x, q: x.q + ' (Q' + (i+1) + ')'})));
  }
  State.eqQuestions = eq.slice(0,120);
  State.floodQuestions = fq.slice(0,120);
  State.fireQuestions = fi.slice(0,120);

  // long precautions library
  for(let i=1;i<=350;i++){
    State.longPrecautions.push(`Precaution ${i}: Keep updated emergency contact lists; run drills and check equipment regularly. (Ref ${i})`);
  }
})();

/* populate long precautions in DOM */
(function populatePrecautions(){
  const ul = document.getElementById('longPrecautionsList');
  if(!ul) return;
  State.longPrecautions.forEach(txt=>{
    const li = document.createElement('li');
    li.textContent = txt;
    ul.appendChild(li);
  });
})();

/* toast helper */
function showToast(msg, type='info'){
  const t = document.createElement('div');
  t.textContent = msg;
  t.style.position='fixed'; t.style.right='18px'; t.style.bottom='18px'; t.style.padding='10px 14px';
  t.style.borderRadius='10px'; t.style.zIndex=99999; t.style.boxShadow='0 10px 30px rgba(0,0,0,0.12)';
  if(type==='ok'){ t.style.background='linear-gradient(90deg,#10b981,#059669)'; t.style.color='#fff'; }
  else if(type==='bad'){ t.style.background='linear-gradient(90deg,#ef4444,#f97316)'; t.style.color='#fff'; }
  else { t.style.background='linear-gradient(90deg,#fff,#fffef7)'; t.style.color='#041025'; }
  document.body.appendChild(t);
  setTimeout(()=>{ t.style.transition='opacity 400ms, transform 400ms'; t.style.opacity=0; t.style.transform='translateY(12px)'; setTimeout(()=>t.remove(),420); },1600);
}

/* update sidebar xp/prep */
function updateSidebar(){
  $('#xpVal').textContent = State.xp;
  const prep = Math.min(99, Math.round(((State.eq.stability) + (State.flood.water) + (State.fire.level))/3));
  $('#prepVal').textContent = prep + '%';
  $('#prepBar').style.width = prep + '%';
  $('#prepBarInner') && ($('#prepBarInner').style.width = prep + '%');
  // badges
  if(State.eq.xp > 120 && !State.badges.has('Mud Tactician')){ State.badges.add('Mud Tactician'); $('#badge2').textContent='🪵 Mud Tactician'; showToast('Badge unlocked: Mud Tactician','ok'); }
  if(State.flood.score > 400 && !State.badges.has('Flood Savvy')){ State.badges.add('Flood Savvy'); $('#badge2').textContent='🌊 Flood Savvy'; showToast('Badge unlocked: Flood Savvy','ok'); }
  if(State.fire.score > 250 && !State.badges.has('Fire Aware')){ State.badges.add('Fire Aware'); $('#badge2').textContent='🔥 Fire Aware'; showToast('Badge unlocked: Fire Aware','ok'); }
}

/* ========== EARTHQUAKE QUIZ FLOW ========== */
$('#eqTotal') && ($('#eqTotal').textContent = State.eqQuestions.length);

function startEqQuiz(){
  State.eq.qIdx = -1;
  renderNextEq();
  goTo('earthquakeQuiz');
}

function renderNextEq(){
  State.eq.qIdx = (State.eq.qIdx + 1) % State.eqQuestions.length;
  const q = State.eqQuestions[State.eq.qIdx];
  $('#eqQuestionTitle').textContent = q.q;
  $('#eqChoices').innerHTML = '';
  q.choices.forEach((c,i)=>{
    const b = document.createElement('button');
    b.className = 'quiz-option';
    b.textContent = c; b.style.display='block'; b.style.margin='6px 0'; b.style.padding='10px'; b.style.borderRadius='8px';
    b.onclick = ()=> submitEqAnswer(i);
    $('#eqChoices').appendChild(b);
  });
  $('#eqQNum').textContent = (State.eq.qIdx + 1);
  $('#eqTotal').textContent = State.eqQuestions.length;
}

function submitEqAnswer(idx){
  const q = State.eqQuestions[State.eq.qIdx];
  $$('#eqChoices .quiz-option').forEach(b=>b.disabled=true);
  const building = $('#buildingVisual');
  if(idx === q.correct){
    State.eq.score += 10; State.eq.xp += 10; State.xp += 10;
    correctTone(); showToast('Correct — building stabilizes','ok');
    building.classList.remove('shake-med','shake-fast'); building.classList.add('shake-slow');
    setTimeout(()=>building.classList.remove('shake-slow'),900);
    State.eq.stability = Math.min(100, State.eq.stability + 6);
  } else {
    State.eq.score += 2; State.xp += 2;
    wrongTone(); showToast('Wrong — building shakes stronger','bad');
    building.classList.remove('shake-slow'); building.classList.add('shake-med');
    $('#mudSplash').style.opacity = 1; $('#mudSplash').style.transform='translateY(-10px)';
    setTimeout(()=>{ $('#mudSplash').style.opacity=0; $('#mudSplash').style.transform='translateY(40px)'; },900);
    State.eq.stability = Math.max(0, State.eq.stability - 10);
    shakeRumble(700);
  }
  $('#eqScore').textContent = State.eq.score; $('#eqXP').textContent = State.eq.xp;
  updateEarthVisuals(); updateSidebar();
  setTimeout(()=> renderNextEq(),900);
}

function updateEarthVisuals(){
  $('#stabilityBar').style.width = State.eq.stability + '%'; $('#stabilityText').textContent = State.eq.stability + '%';
  const b = $('#buildingVisual');
  if(State.eq.stability <= 30){
    b.classList.add('tilt-left'); setTimeout(()=>b.classList.remove('tilt-left'),900);
    $('#groundCrack').style.opacity = Math.min(1,(30-State.eq.stability)/30);
    if(State.eq.stability <= 8){
      b.classList.add('fall'); showToast('Simulation: building collapsed — reset to continue','bad');
    }
  } else {
    $('#groundCrack').style.opacity = 0; b.classList.remove('tilt-left','tilt-right','fall');
  }
}

function simulateShake(level){
  const b = $('#buildingVisual');
  b.classList.remove('shake-slow','shake-med','shake-fast');
  if(level==='fast'){ b.classList.add('shake-fast'); shakeRumble(900); }
  else if(level==='med'){ b.classList.add('shake-med'); shakeRumble(500); }
  else { b.classList.add('shake-slow'); }
  $('#mudSplash').style.opacity=1; $('#mudSplash').style.transform='translateY(-10px)';
  setTimeout(()=>{ $('#mudSplash').style.opacity=0; $('#mudSplash').style.transform='translateY(40px)'; },900);
}

function resetEarth(){
  State.eq = { stability:80, score:0, xp:0, qIdx:-1 };
  $('#eqScore').textContent = 0; $('#eqXP').textContent = 0; updateEarthVisuals(); updateSidebar();
  showToast('Earthquake simulation reset','ok');
}

/* ========== FLOOD QUIZ FLOW ========== */
function startFloodQuiz(){
  State.flood.qIdx = -1; renderNextFlood(); goTo('floodQuiz');
}

function renderNextFlood(){
  State.flood.qIdx = (State.flood.qIdx + 1) % State.floodQuestions.length;
  const q = State.floodQuestions[State.flood.qIdx];
  $('#fQuestionTitle').textContent = q.q; $('#fChoices').innerHTML = '';
  q.choices.forEach((c,i)=>{
    const b = document.createElement('button'); b.className='quiz-option'; b.textContent=c; b.style.display='block'; b.style.margin='6px 0'; b.style.padding='10px'; b.style.borderRadius='8px';
    b.onclick = ()=> submitFloodAnswer(i); $('#fChoices').appendChild(b);
  });
}

function submitFloodAnswer(idx){
  const q = State.floodQuestions[State.flood.qIdx];
  $$('#fChoices .quiz-option').forEach(b=>b.disabled=true);
  if(idx === q.correct){
    State.flood.score += 20; State.xp += 12; State.flood.water = Math.max(0, State.flood.water - 8);
    correctTone(); showToast('Correct — water lowered', 'ok');
    waterPlop();
  } else {
    State.flood.score += 3; State.xp += 3; State.flood.water = Math.min(100, State.flood.water + 10);
    wrongTone(); showToast('Wrong — water rises', 'bad'); waterPlop(); shakeRumble(200);
  }
  $('#fScore').textContent = State.flood.score; updateWaterVisuals(); updateSidebar();
  setTimeout(()=> renderNextFlood(),900);
}

function updateWaterVisuals(){
  $('#waterLayer').style.height = State.flood.water + '%';
  $('#waterBar').style.width = State.flood.water + '%';
  $('#waterPct').textContent = State.flood.water + '%';
  const floats = [$('#floatA'),$('#floatB'),$('#floatC')];
  floats.forEach((el,idx)=>{
    const base = [40,60,46][idx]; if(el) el.style.bottom = (base + Math.round(State.flood.water/2)) + 'px';
  });
  if(State.flood.water >= 98) showToast('Simulation: water reached roof level!', 'bad');
}

function changeWater(delta){
  State.flood.water = Math.max(0, Math.min(100, State.flood.water + delta)); updateWaterVisuals(); showToast('Adjusted water level','info'); waterPlop(); updateSidebar();
}

function resetFlood(){
  State.flood = { water:20, score:0, items:0, qIdx:-1 };
  $('#fScore').textContent = 0; $('#itemsRescued').textContent = 0; updateWaterVisuals();
  ['floatA','floatB','floatC'].forEach(id => document.getElementById(id).classList.remove('saved'));
  showToast('Flood simulation reset','ok'); updateSidebar();
}

/* Floats rescue */
['floatA','floatB','floatC'].forEach((id, idx)=>{
  const el = document.getElementById(id);
  if(!el) return;
  el.addEventListener('click', ()=>{
    if(el.classList.contains('saved')){ showToast('Already rescued','info'); return; }
    el.classList.add('saved'); State.flood.items += 1; State.flood.score += 80; State.xp += 8;
    document.getElementById('itemsRescued').textContent = State.flood.items;
    document.getElementById('fScore').textContent = State.flood.score; updateWaterVisuals();
    correctTone(); showToast('Rescued item! +80 pts','ok'); updateSidebar();
  });
});

/* ========== FIRE QUIZ FLOW & ANIMATION ========== */
function startFireQuiz(){ State.fire.qIdx = -1; renderNextFire(); goTo('fireQuiz'); }

function renderNextFire(){
  State.fire.qIdx = (State.fire.qIdx + 1) % State.fireQuestions.length;
  const q = State.fireQuestions[State.fire.qIdx];
  $('#fireQuestionTitle').textContent = q.q; $('#fireChoices').innerHTML = '';
  q.choices.forEach((c,i)=>{
    const b = document.createElement('button'); b.className='quiz-option'; b.textContent=c; b.style.display='block'; b.style.margin='6px 0'; b.style.padding='10px'; b.style.borderRadius='8px';
    b.onclick = ()=> submitFireAnswer(i); $('#fireChoices').appendChild(b);
  });
}

function submitFireAnswer(idx){
  const q = State.fireQuestions[State.fire.qIdx];
  $$('#fireChoices .quiz-option').forEach(b=>b.disabled=true);
  if(idx === q.correct){
    State.fire.score += 15; State.xp += 10; State.fire.level = Math.max(0, State.fire.level - 8);
    correctTone(); showToast('Correct — fire reduced','ok'); fireCrackle();
    reduceFlames();
  } else {
    State.fire.score += 3; State.xp += 3; State.fire.level = Math.min(100, State.fire.level + 12);
    wrongTone(); showToast('Wrong — fire spreads','bad'); fireCrackle(); increaseFlames();
  }
  $('#fiScore').textContent = State.fire.score; updateFireVisuals(); updateSidebar();
  setTimeout(()=> renderNextFire(),900);
}

function igniteFire(){
  State.fire.level = Math.min(100, State.fire.level + 18); updateFireVisuals(); fireCrackle(); showToast('Small fire ignited (simulation)','bad');
}
function extinguishFire(){
  // random success chance based on current level
  const chance = Math.random() * 100;
  if(chance > State.fire.level){
    State.fire.level = Math.max(0, State.fire.level - 25); correctTone(); showToast('Extinguish succeeded','ok'); reduceFlames();
  } else {
    State.fire.level = Math.min(100, State.fire.level + 10); wrongTone(); showToast('Extinguish partially failed — fire grew','bad'); increaseFlames();
  }
  updateFireVisuals(); updateSidebar();
}
function resetFire(){
  State.fire = { level:0, score:0, qIdx:-1 }; $('#fiScore').textContent = 0; updateFireVisuals(); reduceFlames(true); showToast('Fire simulation reset','ok'); updateSidebar();
}

function updateFireVisuals(){
  $('#fireBar').style.width = State.fire.level + '%'; $('#firePct').textContent = State.fire.level + '%';
  const flames = $('#flames'); const smoke = $('#smoke');
  if(State.fire.level > 0){
    flames.style.opacity = Math.min(1, 0.3 + State.fire.level/120);
    smoke.style.opacity = Math.min(0.9, 0.1 + State.fire.level/80);
  } else { flames.style.opacity = 0; smoke.style.opacity = 0; }
}

function increaseFlames(){
  const flames = $('#flames'); flames.style.opacity = Math.min(1, (parseFloat(flames.style.opacity || 0) + 0.25));
  const smoke = $('#smoke'); smoke.style.opacity = Math.min(0.9, (parseFloat(smoke.style.opacity || 0) + 0.2));
}
function reduceFlames(force=false){
  const flames = $('#flames'); const smoke = $('#smoke');
  if(force){ flames.style.opacity = 0; smoke.style.opacity = 0; return; }
  flames.style.opacity = Math.max(0, (parseFloat(flames.style.opacity || 0) - 0.35));
  smoke.style.opacity = Math.max(0, (parseFloat(smoke.style.opacity || 0) - 0.25));
}

/* ========== Region & misc utilities ========== */
function selectRegion(name){
  State.region = name; $('#selectedRegion').textContent = name; $('#regionNotes').textContent = name + ' selected — quizzes tailored to typical hazards.'; showToast('Region set to ' + name,'ok');
}

/* printing safety card */
function printCard(kind){
  let html = '';
  if(kind==='earthquake'){
    html = `<h2>Earthquake Safety Card</h2><ul><li>Drop, Cover & Hold On</li><li>Stay away from windows</li><li>After shaking, check for injuries</li></ul>`;
  } else if(kind==='flood'){
    html = `<h2>Flood Safety Card</h2><ul><li>Move to higher ground</li><li>Avoid moving water</li><li>Keep medicines waterproof</li></ul>`;
  } else {
    html = `<h2>Fire Safety Card</h2><ul><li>Sound alarm & evacuate</li><li>Use extinguisher if trained</li><li>Do not re-enter until cleared</li></ul>`;
  }
  const w = window.open('','_blank'); w.document.write('<html><head><title>Safety Card</title></head><body style="font-family:Arial;padding:18px">' + html + '</body></html>'); w.document.close();
}

/* quick drill */
function startDrill(){ showToast('Quick drill: Earthquake quiz started', 'ok'); startEqQuiz(); }

/* export CSV */
function exportCSV(){ const rows = [['name','role','score'],['Aarav Kumar','student',980],['Meera Singh','student',870],['You','student',State.xp]]; const csv = rows.map(r=>r.join(',')).join('\n'); const blob = new Blob([csv], {type:'text/csv'}); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href=url; a.download='leaderboard.csv'; a.click(); URL.revokeObjectURL(url); }

/* initialize UI */
function init(){
  try{ $('#eqStartBtn').addEventListener('click', ()=>startEqQuiz()); }catch(e){}
  try{ $('#fStartBtn').addEventListener('click', ()=>startFloodQuiz()); }catch(e){}
  try{ $('#fireStartBtn').addEventListener('click', ()=>startFireQuiz()); }catch(e){}
  updateEarthVisuals(); updateWaterVisuals(); updateFireVisuals(); updateSidebar();
  setTimeout(()=>showToast('Tip: Answer carefully — visuals & sounds react to your choices!', 'ok'),800);
}
init();

/* Expose for debug */
window.AlertEd = { State, startEqQuiz, startFloodQuiz, startFireQuiz, simulateShake, changeWater, igniteFire, extinguishFire, resetEarth, resetFlood, resetFire };

</script>
</body>
</html>
